# Generated by Django 4.2.1 on 2023-05-18 06:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pybo", "0003_answer_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answer", old_name="update_at", new_name="updated_at",
        ),
    ]
