# Generated by Django 4.2.1 on 2023-05-10 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0002_rename_created_at_question_create_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question", old_name="create_date", new_name="created_at",
        ),
    ]
