# Generated by Django 4.2.1 on 2023-05-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0003_rename_create_date_question_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="created_at",
            field=models.DateTimeField(verbose_name="date published"),
        ),
    ]
